# -*- coding: utf-8 -*-
"""SKLearn SVR

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPczZKjWexfPH9Ke1gsp_pOe2luTfg6w
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
 
 
data = pd.read_csv('Salary_Data.csv')

data.info()

data.head()

import numpy as np
 
 
X = data['YearsExperience']
y = data['Salary']
X = X[:,np.newaxis]

X

y

from sklearn.svm import SVR
model  = SVR(C=1000, gamma=0.05, kernel='rbf')
model.fit(X,y)

import matplotlib.pyplot as plt
plt.scatter(X, y)
plt.plot(X, model.predict(X))

